# Generated by Django 4.1.4 on 2022-12-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220)),
                ('link_type', models.CharField(choices=[('book', 'Book'), ('kindle', 'Kindle Book'), ('generic', 'Generic')], default='book', max_length=7)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_price', models.FloatField(default=0)),
                ('old_price', models.FloatField(default=0)),
                ('price_difference', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['price_difference', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.link')),
            ],
            options={
                'ordering': ['price', 'created'],
            },
        ),
    ]
