# Generated by Django 4.1.4 on 2022-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='situation',
            field=models.CharField(choices=[('pending', 'Pending'), ('calculed', 'Calculed')], default='pending', max_length=8),
        ),
    ]
